
spring:
  level:
    root: INFO
    com.example.SBEAM: DEBUG
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/SBEAM?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  alipay:
    app-id: 2021000147697711
    app-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDXEts0FjPMsiiY8oHNMpK9JFTBlO2413hQKcVl3VC3NJojw0bALaFvz3jutSaPil/jzja8F/9eBwKVhy53ydY2yFHlp1qfX8idGYd+bDZrak2e/5nJMbYFEM+XfJOk0qhKVzcdrZsBXvv3gvcKyvrfdkNAhMDgn92y68YHODdLPCBU6KFUdtcBiu7i5vLWxynltWSB5dt1G6eqBpAwOGOumLuCWh8pSDc+qBKLKru71ukVuj3TUtHAWF8zgsaupzcCv2RTMRdzjYOCIrBzghPTJizQfrOfeWWjpSGw/5J2fPCRS1KiGmMCMB/nHfLpdlaEXMKlQsnX+PWMNlqSw+MJAgMBAAECggEBAKVtio/Y2AUFsDZcqbyUvsufK1Yu4F8B1TgLuRruDUytuDXz2PKu5nKjKciqK7vS2ojVr8IjzzeausEa1oIrDIrcsCmt/QWDXkKARXjXcVBT1tqKjdZ0VyY0VQiXONVZdzqfNPSt+QEn9zTdVnnFwQuq4nW45sagEJ2zvoEFG3rQnWYjjhb+LHHU9nyp2dH8BuQyzvPf7m83/J00GhjlvngDlBZHqB9H9FRbNJBucutlTwors4up8eghTH85KOloZdtuAzBtddlabW+0NEUoLhu2rxFBWKX1D7uEli5ol/pNccM25wKhWkluSj6wL+cfiw3brJ86/hKVcdTuWxpT4AECgYEA/19L4FXrZPRImjALvp7porMoVcAuwDntKr2bQJhvIo7LdS1A0EtpGoQV3JtnXRcP1KvY3e5dyE8mLGcATJ+lgGMJ2A8uLj7p86d9IjnEZ0O6UgT7B/yja6xmjZqX5iy+ctia/jZG/R7WlkwazuRAWGR0Sc7G8S+JRPTaIHDfvAECgYEA15ozRzmv5X7KghJN3jcig7ezFZlXlDmEz/2qxRFcM+qYODW+6iApBq0yZAfPQa/kq3HLPn3SRFD8yklgHs5WBkur5+YtsMO7tLuyAMSyBdHb10K772gUXerFJ3Bi4IFbLSst43AistPsbbHFj7e3aUSWCod0a4oN6DVn8BXCRwkCgYBZHZJG6PTKOA0V8WpHzQDPDCIpOnWWEyDWZ3BELG2r65TIgVA63/X/kNRoNbruW1vk5Us6tzH28tfpatBJ7PQ+R1FqGnINJVtS8cHTLcGCH7pnYOGROfJ1YqYvCCG16ytSvI/p4lsHfbl4nXpFdJWXwwZps0TtaZ9HdwKfi4QoAQKBgQCcpWycU015cKWx25q32Vc6XD3Bc6guCZx1gdiRVgunrMrsDCCp+rPUJgJ2qzXqg+Ggrwz8Wm5rNGx2jNlJiKD38gL0eki4JX470iOCa2bs04zm2ZWyW+xwUCLuhLlSZKnaJ4Uvukl7pH4jNQZVZSXdVfetrrznZWa1UBg0V5rQAQKBgQD3z9FKkAd/wAVGS15jxdkt5YtC4jY0p7dSMK6SxKo//lO1YlV3KjF5qInxDvIDUuTR08YliQ2nF3WiQ2WVUhNDQWhLVqwN9VxzdseSBI41wFryE2XZNI7laUNUQntxynfEZp/Om61JvfCu9GqnsiL96iMLFiTDN8UTZsF+I3EluQ==
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1xLbNBYzzLIomPKBzTKSvSRUwZTtuNd4UCnFZd1QtzSaI8NGwC2hb8947rUmj4pf4842vBf/XgcClYcud8nWNshR5adan1/InRmHfmw2a2pNnv+ZyTG2BRDPl3yTpNKoSlc3Ha2bAV7794L3Csr633ZDQITA4J/dsuvGBzg3SzwgVOihVHbXAYru4uby1scp5bVkgeXbdRunqgaQMDhjrpi7glofKUg3PqgSiyq7u9bpFbo901LRwFhfM4LGrqc3Ar9kUzEXc42DgiKwc4IT0yYs0H6zn3llo6UhsP+SdnzwkUtSohpjAjAf5x3y6XZWhFzCpULJ1/j1jDZaksPjCQIDAQAB
    notify-url: http://kt36jp.natappfree.cc/alipay/notify
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    gateway-url: https://openapi.alipaydev.com/gateway.do
    return-url: http://你的公网地址/alipay/return

server:
  port: 8080
