
spring:
  level:
    root: INFO
    com.example.SBEAM: DEBUG
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/SBEAM?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
alipay:
  appId: 2021000147697711
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCPH5/vSP06LD5uJ3uKmWu9LnGvXxYcbKeiY17VOafI8PdOzmmAFVfZZ9EvjF/ZbUhcn7G4A0s3pvbo37ZmMCInO87hmoF2pKAfSfRlsilezaKIqLvavtldwFPlnautNJjSlW6cKgf58I8jz/a4OG66G2j0q9qYNnsc3QFohTg+SMNXlT6PeEd+x/6leBYMIEtiLCl/rxBkYzx7V3hct/LkIp0CtbU69mV32QldbfZy4qeXz4L1qvhrw4GROyXBKKaO6piOxaI0GPYIIfiG9PBzWW/4TOHjcolACV3X6rp38oITIfV7ostIXbIWel0xxlLDNdJBc4sFT09Qo82LyzXHAgMBAAECggEAMCo9YYKXrYcML3fcDIWbC1xg59rBDynFtFFqraksfOQS5hNyz6bfHIviivTboMk1K+6WGU4Kdx0aRL5cnMEgDUIEWknrvaijNkRmGf8+Cuh7BTB7n57QectqsIBCMRTdRSkCw00lyAgbs7qd1dsv8DOfO4/GDalv/wOlIK6MgfDpiaz+S4sRJoXbLtE5YSrOLknKRayU5hGxmXGGCWExNNYVMgEpU2Q9Mt1GeN64Gn1JJOGaTazw0QivzeOUPqtM9calP8xAXGFmx9dZmDCGh0WwJFilJ0ilHkOnnoxjQ4s4kxcOlTsy0kmuw2zvjwpp5Ol8XwKUoVpQ3/1r6vhsMQKBgQDoC7m8h4oavirITpYaODo+XbUxtX/mjMhHl6sSug6kBusk7+Fsvmgt0CX0xmrOSUyg1B2iFG609Z2zk2YhssXt72nSmPmauy2QMRFENY6oG4pvoK/gO3j6gG5KPuDsxqcGEASR1LCYxYJUDgP1wiRpZfr+Zn8f9PZyNEQRCjOgHwKBgQCd5fNNpwQ1iEWgbDZa7wvLPM6evpQeE4/dI53qxdQ2r4nVmsI62mT1QoY/u5LAbNiZSyrHRVKdEg072S7pxjdoKPkwBd4KvP/WI2q22ozwNfWFdHLL3liSF6lmwB7BxcmtmFrOuf8LyI2b7wvBhVya2SsqfJxee3XYOHjPLYoVWQKBgDK87Z31nRL/5ebqmBOfm8yrPMVjxFWrDtfop/VuTWk8QgpPkWDvuWPbEZGWGSCGEoVQHDKmeRaEZjkvz7MqnfDK2r67yEg3CV1v/TCG7WyAqSKDZjGHj4pmrrb5TME5JqhCtF0Wvo6JEVhDwEXqb3/EVr9ttfpM295Y41E+g89NAoGAZvdaRwwf6YzY4rlOZNQ326vmjYx36HkXOr0MMNoa/iJQfvPxrxFV/r4H762xEDyqrqRe3B2vtu/bo2iIeDgjT5BQl2lsF5KSPyFPaLhyaf62AfYjGiD/nx1BAdlM9U22q7aLmP2ffR6mgcZL40HFVtFBne4uxko6WerRlUD8J9kCgYEA3g0dQX9PXw7jJ1oxYDoGUPBgvBFQKFSHD7cDRUauUW4rDNm/5Jxiap811X3QWWcTH29Ycs9AbfGZa2zpnQo45Hugi8VhhOI7Os7y3hTeR8MGtaB7MM/IqGMWkdp5aKxNlXBd5OHQBysYZj1bpHNT2zsrt+Co+S2uHwldDb+OPwc=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoOb2DbffE5vanVXlyYreMRWdh9Fc9NQx/5EDls1yuXr1Fj30v1QKScRk3TbpKC626dl0TsSHMI0ZuLJHJYr1fnHNcC1OwHmGOluGYw2SEQfzxl3mzmlrSFhkDXHeWSzRrptgByRwIUM7IgwQEGj7VbAL4C8xKqqLnfA8jJUgljj8f1GwyTHKT6u9AZ65ooex++rugZgVwVAqvPqHh3eAF/Q60uy1ycE8bcuUQk5T7/CbfQmPAVDHDqUd13YOvy5Z5QLnBi5h/VZ8+X4/zj32GAl+ufnR7kcPTWUFtzV4iALnjNO2L6+5RW6RrPjAnXve1hOrYpRwpxBlsiBaXkpQIwIDAQAB
  notifyUrl: http://r9exwp.natappfree.cc/api/alipay/notify
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  return-url: http://r9exwp.natappfree.cc/api/alipay/return
dashscope:
  api-key: sk-9fecf88080a4456f9b52dd0ba03e74c0
  model-endpoint: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation


server:
  port: 8080
